import { CommonModule } from '@angular/common';
import { MaterialModule } from '../../materials/material.module';
import { NgModule } from '@angular/core';
import { PaginatorModule } from 'primeng/paginator';
import { PerformanceChartComponent } from './performance-chart/performance-chart.component';
import { PerformanceTable2Component } from './performance-table2/performance-table2.component';
import { PerformanceTableComponent } from './performance-table/performance-table.component';
import { SharedAppModule } from '../shared/shared.module';
import { TransformCurrencyPipeModule } from '../../pipe/transform-currency/transform-currency.pipe';
import { WidgetAppRoutingModule } from './widget-app-routing.module';

// import { TableModule } from 'primeng/table';



@NgModule({
  declarations: [
    // PermitFilterComponent,
    // PermitListComponent,
    // PermitOverviewTabComponent,
    // PermitChangeRequestTabComponent,
    // PermitConditionsTabComponent,
    // PermitFpnTabComponent,
    // PermitInspectionsTabComponent,
    // PermitImagesAndFilesTabComponent,
    // PermitReinstatementTabComponent,
    // PermitCommentsTabComponent,
    // PermitActivityLogTabComponent,
    // ViewPermitChangeRequestComponent,
    // ViewPermitFpnComponent,
    // ViewPermitInspectionComponent,
    // CreatePermitSelectLocationComponent,
    // CreatePermitDrawMapComponent,
    // CreatePermitSelectConditionsComponent,
    // CreatePermitFormComponent,
    // CreatePermitSummaryComponent,
    // CreatePermitConfirmationComponent,
    // BulkUploadComponent,
    // UserListingComponent,
    // CreateUserComponent,
    // RoleListingComponent,
    // CreateRoleComponent,
    // CreateOrganisationComponent,
    // OrganisationListingComponent,
    // CreateReinstatementComponent,
    // ViewBulkuploadDataComponent,
    // ElginmapComponent,
    // TransformDatePipe,
    // TransformDateTimePipe,
    // FileUploadComponent,
    // CancelPermitConfirmationComponent,
    // PermitQuickFilterComponent,
    // AddCommentComponent,
    // DataDiffA3Component,
    // InvalidControlScrollDirective,
    // HelperTextPopoverContainerComponent,
    // HelperTextComponent,
	  // DueListWidgetComponent,
    // WorkReportListComponent,
    // PotentialFinanceLiableComponent,
    // PermitMapTabComponent,
    // SiteDetailsComponent,
    // PermitMapDesignationTabComponent,
    // CreateReinstatementFormComponent,
    // RaiseChangeReqConfirmationComponent,
    // ViewPermitCommentsComponent,
    // ReinstatementImagesAndFilesComponent,
    // CreateReinstatementSummaryComponent,
    // GlobalFilterComponent,
    PerformanceTableComponent,
    PerformanceTable2Component,
    PerformanceChartComponent,
  ],
  imports: [
    CommonModule,
    // WidgetAppRoutingModule,
    MaterialModule,
    // FileUploadModule,
    // SharedAppModule,
    // NgxMatDatetimePickerModule,
    // NgxMatTimepickerModule,
    // NgxMatNativeDateModule,
    // OptionalSelectDirectiveModule,
    // NgxTextDiffModule,
    // TableModule,
    // TransformCurrencyPipeModule,
    // HelperTextPopoverDirectiveModule,
    // PaginatorModule
  ],
  exports: [
    // PermitFilterComponent,
    // PermitListComponent,
    // PermitOverviewTabComponent,
    // PermitChangeRequestTabComponent,
    // PermitConditionsTabComponent,
    // PermitFpnTabComponent,
    // PermitInspectionsTabComponent,
    // PermitImagesAndFilesTabComponent,
    // PermitReinstatementTabComponent,
    // PermitCommentsTabComponent,
    // PermitActivityLogTabComponent,
    // ViewPermitChangeRequestComponent,
    // UserListingComponent,
    // RoleListingComponent,
    // OrganisationListingComponent,
    // CreateReinstatementComponent,
    // ViewBulkuploadDataComponent,
    // ElginmapComponent,
    // FileUploadComponent,
    // CreatePermitDrawMapComponent,
    // CreatePermitSelectConditionsComponent,
    // CreatePermitFormComponent,
    // CreatePermitSummaryComponent,
    // CreatePermitConfirmationComponent,
    // CreatePermitSelectLocationComponent,
    // PermitQuickFilterComponent,
    // AddCommentComponent,
    // DataDiffA3Component,
    // ViewPermitFpnComponent,
    // CancelPermitConfirmationComponent,
    // ViewPermitInspectionComponent,
    // DueListWidgetComponent,
    // HelperTextPopoverContainerComponent,
    // HelperTextComponent,
    // WorkReportListComponent,
    // PotentialFinanceLiableComponent,
    // PermitMapTabComponent,
    // PermitMapDesignationTabComponent,
    // RaiseChangeReqConfirmationComponent,
    // ViewPermitCommentsComponent,
    // CreateReinstatementFormComponent,
    // SiteDetailsComponent,
    // RaiseChangeReqConfirmationComponent,
    // ReinstatementImagesAndFilesComponent,
    // CreateReinstatementSummaryComponent,
    // GlobalFilterComponent,
    PerformanceTableComponent,
    PerformanceTable2Component,
    PerformanceChartComponent,
  ]
})
export class WidgetAppModule { }
